ASPLabb1/Controllers/HistoriesController.cs
using ASPLabb1.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASPLabb1.Controllers;

public class HistoriesController : Controller
{
	private readonly ApplicationDbContext _context;

	public HistoriesController(ApplicationDbContext context)
	{
		_context = context;
	}

	// GET: Histories
	public async Task<IActionResult> Index()
	{
		var applicationDbContext = _context.Historys.Include(h => h.Personal).Include(h => h.TimeOffApplication);
		return View(await applicationDbContext.ToListAsync());
	}

	// GET: Histories/Details/5
	public async Task<IActionResult> Details(int? id)
	{
		if (id == null)
		{
			return NotFound();
		}

		var history = await _context.Historys
			.Include(h => h.Personal)
			.Include(h => h.TimeOffApplication)
			.FirstOrDefaultAsync(m => m.Id == id);
		if (history == null)
		{
			return NotFound();
		}

		return View(history);
	}
}

ASPLabb1/Controllers/PersonalsController.cs
using ASPLabb1.Data;
using ASPLabb1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ASPLabb1.Controllers
{
	public class PersonalsController : Controller
	{
		private readonly ApplicationDbContext _context;

		public PersonalsController(ApplicationDbContext context)
		{
			_context = context;
		}

		// GET: Personals
		public async Task<IActionResult> Index()
		{
			return View(await _context.Personals.ToListAsync());
		}

		// GET: Personals/Details/5
		public async Task<IActionResult> Details(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var personal = await _context.Personals
				.FirstOrDefaultAsync(m => m.Id == id);
			if (personal == null)
			{
				return NotFound();
			}

			return View(personal);
		}

		// GET: Personals/Create
		public IActionResult Create()
		{
			return View();
		}

		// POST: Personals/Create
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Create([Bind("Id,Name")] Personal personal)
		{
			if (ModelState.IsValid)
			{
				_context.Add(personal);
				await _context.SaveChangesAsync();
				return RedirectToAction(nameof(Index));
			}
			return View(personal);
		}

		// GET: Personals/Edit/5
		public async Task<IActionResult> Edit(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var personal = await _context.Personals.FindAsync(id);
			if (personal == null)
			{
				return NotFound();
			}
			return View(personal);
		}

		// POST: Personals/Edit/5
		// To protect from overposting attacks, enable the specific properties you want to bind to.
		// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Personal personal)
		{
			if (id != personal.Id)
			{
				return NotFound();
			}

			if (ModelState.IsValid)
			{
				try
				{
					_context.Update(personal);
					await _context.SaveChangesAsync();
				}
				catch (DbUpdateConcurrencyException)
				{
					if (!PersonalExists(personal.Id))
					{
						return NotFound();
					}
					else
					{
						throw;
					}
				}
				return RedirectToAction(nameof(Index));
			}
			return View(personal);
		}

		// GET: Personals/Delete/5
		public async Task<IActionResult> Delete(int? id)
		{
			if (id == null)
			{
				return NotFound();
			}

			var personal = await _context.Personals
				.FirstOrDefaultAsync(m => m.Id == id);
			if (personal == null)
			{
				return NotFound();
			}

			return View(personal);
		}

		// POST: Personals/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var personal = await _context.Personals.FindAsync(id);
			if (personal != null)
			{
				_context.Personals.Remove(personal);
			}

			await _context.SaveChangesAsync();
			return RedirectToAction(nameof(Index));
		}

		private bool PersonalExists(int id)
		{
			return _context.Personals.Any(e => e.Id == id);
		}
	}
}

ASPLabb1/Controllers/TimeOffApplicationsController.cs
using ASPLabb1.Data;
using ASPLabb1.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace ASPLabb1.Controllers;

public class TimeOffApplicationsController : Controller
{
    private readonly ApplicationDbContext _context;

    public TimeOffApplicationsController(ApplicationDbContext context)
    {
        _context = context;
    }

    // GET: TimeOffApplications
    public async Task<IActionResult> Index()
    {
        var applicationDbContext = _context.TimeOffApplications.Include(t => t.Personal);
        return View(await applicationDbContext.ToListAsync());
    }

    // GET: TimeOffApplications/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var timeOffApplication = await _context.TimeOffApplications
            .Include(t => t.Personal)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (timeOffApplication == null)
        {
            return NotFound();
        }

        return View(timeOffApplication);
    }

    // GET: TimeOffApplications/Create
    public IActionResult Create()
    {
        ViewData["PersonalId"] = new SelectList(_context.Personals, "Id", "Name");
        return View();
    }

    // POST: TimeOffApplications/Create
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Id,TypeName,StartDate,EndDate,ApplicationDate,PersonalId")] TimeOffApplication timeOffApplication)
    {
        if (ModelState.IsValid)
        {
            _context.Add(timeOffApplication);
            await _context.SaveChangesAsync();

            History history = new()
            {
                PersonalId = timeOffApplication.PersonalId,
                TimeOffApplicationId = timeOffApplication.Id
            };

            _context.Add(history);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        ViewData["PersonalId"] = new SelectList(_context.Personals, "Id", "Name", timeOffApplication.PersonalId);
        return View(timeOffApplication);
    }

    // GET: TimeOffApplications/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var timeOffApplication = await _context.TimeOffApplications.FindAsync(id);
        if (timeOffApplication == null)
        {
            return NotFound();
        }
        ViewData["PersonalId"] = new SelectList(_context.Personals, "Id", "Name", timeOffApplication.PersonalId);
        return View(timeOffApplication);
    }

    // POST: TimeOffApplications/Edit/5
    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,TypeName,StartDate,EndDate,ApplicationDate,PersonalId")] TimeOffApplication timeOffApplication)
    {
        if (id != timeOffApplication.Id)
        {
            return NotFound();
        }

        if (ModelState.IsValid)
        {
            try
            {
                _context.Update(timeOffApplication);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TimeOffApplicationExists(timeOffApplication.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }
            return RedirectToAction(nameof(Index));
        }
        ViewData["PersonalId"] = new SelectList(_context.Personals, "Id", "Name", timeOffApplication.PersonalId);
        return View(timeOffApplication);
    }

    // GET: TimeOffApplications/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var timeOffApplication = await _context.TimeOffApplications
            .Include(t => t.Personal)
            .FirstOrDefaultAsync(m => m.Id == id);
        if (timeOffApplication == null)
        {
            return NotFound();
        }

        return View(timeOffApplication);
    }

    // POST: TimeOffApplications/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var timeOffApplication = await _context.TimeOffApplications.FindAsync(id);
        if (timeOffApplication != null)
        {
            _context.TimeOffApplications.Remove(timeOffApplication);
        }

        await _context.SaveChangesAsync();
        return RedirectToAction(nameof(Index));
    }

    private bool TimeOffApplicationExists(int id)
    {
        return _context.TimeOffApplications.Any(e => e.Id == id);
    }
}

ASPLabb1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASPLabb1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Daniel Frykman</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
	                        <a class="nav-link text-dark" asp-area="" asp-controller="Personals" asp-action="Index">Personell</a> 
                        </li>
                        <li class="nav-item">
	                        <a class="nav-link text-dark" asp-area="" asp-controller="TimeOffApplications" asp-action="Index">Time off applications</a> 
                        </li>
                        <li class="nav-item">
	                        <a class="nav-link text-dark" asp-area="" asp-controller="Histories" asp-action="Index">History</a> 
                        </li>
                        <li class="nav-item">
	                        <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="Search">Search</a> 
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Search" asp-action="FilterSearch">Search by month</a>
                        </li>
                    </ul>
                    @* <partial name="_LoginPartial" /> *@
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - Daniel Frykman NET23 ASP Labb 1
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>